[package]
name = "hash-crypto"
version = "0.1.0"
authors = ["Max Fillinger <max@max-fillinger.net>"]

[dependencies]
rand = "0.4.0"

[dependencies.openssl]
path = "../rust-openssl/openssl"

[dependencies.openssl-sys]
path = "../rust-openssl/openssl-sys"
